---
apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: aibus-tf-idf-text-classifier-serving-legacy
  annotations:
    scenarios.ai.sap.com/description: "AI Content: TF IDF Text Classifier"
    scenarios.ai.sap.com/name: aibus-tf-idf-text-classifier
    executables.ai.sap.com/description: Legacy Serving Executable for TF IDF Text Classifier
    executables.ai.sap.com/name: aibus-tf-idf-text-classifier-serving-legacy
  labels:
    scenarios.ai.sap.com/id: 887b31df-786e-48c0-8368-34b5f73cdd6c
    ai.sap.com/version: "0.0.2"
spec:
  imagePullSecrets:
  - name: tf-idf-classifier-docker-secret
  inputs:
    artifacts:
    - name: modelArtifactId
  template:
    spec: |
      predictor:
        minReplicas: 1
        containers:
        - name: kserve-container
          image: sti.common.repositories.cloud.sap/text-classifier-inference-legacy:latest
          ports:
          - containerPort: 9001
            protocol: TCP
          env:
          - name: STORAGE_URI
            value: "{{inputs.artifacts.modelArtifactId}}"
          - name: MODEL_URI
            value: /mnt/models/func.pkl
        imagePullSecrets:
        - name: tf-idf-classifier-docker-secret
    apiVersion: serving.kserve.io/v1beta1
